name: Repost Tweets to Bluesky

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  repost:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy atproto requests

    - name: Run the reposting script
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: python reposting_fra_twitter_til_bluesky.py

    - name: Commit updated last_tweet.txt
      if: success()
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add last_tweet.txt
        git commit -m "Update last_tweet.txt with latest tweet ID"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
